[[plugins]]
repo = 'https://github.com/itchyny/lightline.vim'
hook_add = '''
let g:lightline = {
  \ 'separator': { 'left': '', 'right': '' },
  \ }
'''

[[plugins]]
repo = 'nanotech/jellybeans.vim'
hook_add = '''
colorscheme jellybeans
set termguicolors
let g:lightline = {
  \ 'colorscheme': 'jellybeans',
  \ }
'''

